name: Builds Android apk and aab

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Version Code and Version Name
        id: version
        run: |
          echo "version_code=$(./gradlew -q printVersionCode)" >> $GITHUB_ENV
          echo "version_name=$(./gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Build APK and AAB with Gradle
        run: ./gradlew assembleRelease bundleRelease

      - name: Create keystore file
        run: |
          echo ${{ secrets.KEYSTORE_FILE }} | base64 -d > keystore.jks


      - name: Sign APK
        run: |
          jarsigner -keystore keystore.jks \
          -storepass ${{ secrets.STORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -signedjar app/build/outputs/apk/release/app-release-signed.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS_APK }}

      - name: Sign AAB
        run: |
          jarsigner -keystore keystore.jks\
          -storepass ${{ secrets.STORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -signedjar app/build/outputs/bundle/release/app-release.aab \
          app/build/outputs/bundle/release/app-release-signed.aab ${{ secrets.KEY_ALIAS_AAB }}

      - name: Rename APK and AAB
        run: |
          mv app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/app-release-${{ env.version_name }}-${{ env.version_code }}-unsigned.apk
          mv app/build/outputs/bundle/release/app-release-signed.aab app/build/outputs/bundle/release/app-release-${{ env.version_name }}-${{ env.version_code }}.aab

      - name: Upload artefacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: outputs
          path: app/build/outputs/
