name: Builds Android apk and aab

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Version Code and Version Name
        id: version
        run: |
          echo "::set-output name=version_code::$(./gradlew -q printVersionCode)"
          echo "::set-output name=version_name::$(./gradlew -q printVersionName)"

      - name: Build APK and AAB with Gradle
        run: ./gradlew assembleRelease bundleRelease

      - name: Rename APK and AAB
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-${{ steps.version.outputs.version_name }}-${{ steps.version.outputs.version_code }}-unsigned.apk
          mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/app-release-${{ steps.version.outputs.version_name }}-${{ steps.version.outputs.version_code }}.aab

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/release/*-unsigned.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: aab
          path: app/build/outputs/bundle/release/*.aab
