name: Builds Android apk and aab

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon

      - name: Publish Unit Test Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Unit Test Report
          path: app/build/reports/tests/testDebugUnitTest
  build:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Version Code and Version Name
        id: version
        run: |
          echo "version_code=$(./gradlew -q printVersionCode)" >> $GITHUB_ENV
          echo "version_name=$(./gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Build APK and AAB with Gradle
        run: ./gradlew assembleDebug bundleDebug

      - name: Create keystore file
        run: |
          echo ${{ secrets.KEYSTORE_FILE }} | base64 -d > keystore.jks

      - name: Sign APK
        run: |
          jarsigner -keystore keystore.jks \
          -storepass ${{ secrets.STORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -signedjar app/build/outputs/apk/debug/app-debug-signed.apk \
          app/build/outputs/apk/debug/app-debug.apk ${{ secrets.KEY_ALIAS }}

      - name: Sign AAB
        run: |
          jarsigner -keystore keystore.jks \
          -storepass ${{ secrets.STORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -signedjar app/build/outputs/bundle/debug/app-debug-signed.aab \
          app/build/outputs/bundle/debug/app-debug.aab ${{ secrets.KEY_ALIAS }}

      - name: Rename APK and AAB
        run: |
          mv app/build/outputs/apk/debug/app-debug-signed.apk app/build/outputs/apk/debug/app-debug-${{ env.version_name }}-${{ env.version_code }}.apk
          mv app/build/outputs/bundle/debug/app-debug-signed.aab app/build/outputs/bundle/debug/app-debug-${{ env.version_name }}-${{ env.version_code }}.aab

      - name: Upload artefacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: outputs
          path: app/build/outputs/
