name: Instrumented Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          sdk-version: '31.0.0'
          ndk-version: '23.1.7779620'
          java-version: '17'

      - name: Install dependencies
        run: ./gradlew dependencies --no-daemon

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest --no-daemon
