name: Release Android apk and aab

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ env.AWS_REGION }}
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build APK and AAB with Gradle
        run: ./gradlew assembleRelease bundleRelease

      - name: Create keystore file
        run: |
          echo ${{ secrets.KEYSTORE_FILE }} | base64 -d > keystore.jks

      - name: Sign APK
        run: |
          jarsigner -keystore keystore.jks \
          -storepass ${{ secrets.STORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -signedjar app/build/outputs/apk/release/app-release-signed.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

      - name: Sign AAB
        run: |
          jarsigner -keystore keystore.jks \
          -storepass ${{ secrets.STORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          -signedjar app/build/outputs/bundle/release/app-release-signed.aab \
          app/build/outputs/bundle/release/app-release.aab ${{ secrets.KEY_ALIAS }}

      - name: Rename APK and AAB
        run: |
          mv app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/app-release-${{ env.version_name }}-${{ env.version_code }}.apk
          mv app/build/outputs/bundle/release/app-release-signed.aab app/build/outputs/bundle/release/app-release-${{ env.version_name }}-${{ env.version_code }}.aab

      - name: Configure AWS credentials
        run: |
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials

      - name: Install AWS CLI
        run: |
          sudo apt-get -y install awscli

      - name: Push APK to CodeArtifact
        run: |
          aws codeartifact push-package-version \
            --domain ${{ env.AWS_CODEARTEFACT_DOMAIN }} \
            --repository ${{ env.AWS_CODEARTEFACT_REPO }} \
            --package  app-release-${{ needs.build.outputs.version_name }}.apk \
            --format zip \
            --namespace mobile-app \
            --package-version ${{ needs.build.outputs.version_name }} \
            --source app/build/outputs/apk/release/app-release-${{ needs.build.outputs.version_name }}.apk

      - name: Push AAB to CodeArtifact
        run: |
          aws codeartifact push-package-version \
            --domain ${{ env.AWS_CODEARTEFACT_DOMAIN }} \
            --repository ${{ env.AWS_CODEARTEFACT_REPO }} \
            --package app-release-${{ needs.build.outputs.version_name }}.aab \
            --format zip \
            --namespace mobile-app \
            --package-version ${{ needs.build.outputs.version_name }} \
            --source app/build/outputs/bundle/release/app-release-${{ needs.build.outputs.version_name }}.aab

      - name: Update Version
        run: |
          TAG_NAME=v${VERSION}
          ./gradlew setVersion -Pversion=$VERSION
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Update version in build.gradle to $VERSION"
          git tag $TAG_NAME -m "Version $VERSION"
          git push origin $TAG_NAME

      - name: Upload artefacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: outputs
          path: app/build/outputs/